Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.NO_SID_API_LIST = exports.config = void 0;

var e = {
    BASE_URL: {
        development: "https://www.xiaohongshu.com",
        production: "https://www.xiaohongshu.com"
    },
    API_LIST: {
        LOGIN: "/fe_api/burdock/weixin/v2/login/code",
        LOGOUT: "/weixin_mp/thor/logout",
        USER_INFO: "/fe_api/burdock/weixin/v2/login/update_weixin_userinfo",
        CHECK_AUTH_VALIDATE: "/fe_api/burdock/weixin/v2/login/authorization_validate",
        MOBILE_LOGIN: "/fe_api/burdock/weixin/v2/login/mobile",
        GET_PHONE_ZONES: "https://pages.xiaohongshu.com/data/sns/mp_phone_number_zone",
        WX_MOBILE_LOGIN: "/fe_api/burdock/weixin/v2/login/weixin_mobile",
        VFC_CODE: "/fe_api/burdock/weixin/v2/login/identifyCode/send",
        COMMUNITY_HOMEFEEDS: "/fe_api/burdock/weixin/v2/homefeed/personalNotes",
        COMMUNITY_CATEGORIES: "/fe_api/burdock/weixin/v2/homefeed/categories",
        FOLLOW: "/fe_api/burdock/weixin/v2/user/{userId}/follow",
        UNFOLLOW: "/fe_api/burdock/weixin/v2/user/{userId}/unfollow",
        AUTHORFAVED: "/fe_api/burdock/weixin/v2/user/{userId}/collectedNotes",
        SNS_USER_INFO: "/fe_api/burdock/weixin/v2/user/{userId}",
        SNS_NOTE_USER: "/fe_api/burdock/weixin/v2/user/{userId}/notes",
        SNS_OTHER_NOTE_USER: "/fe_api/burdock/weixin/v2/user/{userId}/other/notes",
        SNS_ATTA_NOTE: "/fe_api/burdock/weixin/v2/user/{userId}/atUserNotes",
        SNS_USER_FOLLOWINGS: "/fe_api/burdock/weixin/v2/user/{id}/followings",
        SNS_USER_FOLLOWERS: "/fe_api/burdock/weixin/v2/user/{id}/followers",
        MINE_INFO_DETAIL: "/wx_mp_api/sns/v1/user/me",
        EDIT_MINE_INFO: "/wx_mp_api/sns/v1/user/info",
        VIDEO_NOTE_FEED: "/fe_api/burdock/baidu/v1/notes/{noteId}/videofeed",
        LIKE_NOTE: "/fe_api/burdock/weixin/v2/note/{noteId}/like",
        COLLECT_NOTE: "/fe_api/burdock/weixin/v2/note/{noteId}/collect",
        NOTE_COMMENT_DETAIL: "/fe_api/burdock/weixin/v2/notes/{noteId}/comments",
        SEND_COMMENT: "/fe_api/burdock/weixin/v2/comment",
        SINGLE_FEED: "/fe_api/burdock/weixin/v2/note/{noteId}/single_feed",
        IMAGE_STICKERS: "/fe_api/burdock/weixin/v2/note/{id}/image_stickers",
        RELATED_NOTES: "/fe_api/burdock/weixin/v2/note/{noteId}/related",
        RELATED_NOTE_FEEDS: "/fe_api/burdock/weixin/v2/note/{noteId}/feed",
        NOTE_TAGS: "/fe_api/burdock/weixin/v2/note/{noteId}/tags",
        NOTES_HOT_SEARCH: "/fe_api/burdock/weixin/v2/search/trending",
        SEARCH_NOTES_FROM_KEYWORD: "/fe_api/burdock/weixin/v2/search/notes",
        SEARCH_NOTES_AUTO_COMPLETE: "/fe_api/burdock/weixin/v2/search/recommend",
        SEARCH_NOTES_PLACEHOLDER: "/wx_mp_api/sns/v1/search/placeholder",
        SEARCH_TOPIC: "/fe_api/burdock/weixin/v2/search/one_box",
        GOODS_HOT_SEARCH: "/api/sns/v1/wx_mp/search/trending",
        SEARCH_FROM_KEYWORD: "/api/store/ps/products",
        SEARCH_AUTO_COMPLETE: "/api/sns/v1/wx_mp/search/recommend",
        HOMEFEEDS: "/api/store/hf/feeds",
        SEARCH_USERS_FROM_KEYWORD: "/fe_api/burdock/weixin/v2/search/users",
        CHECK_IF_NEW_USER: "/api/store/mc/type/v1",
        FULISHE_CATEGORIES_BANNERS: "/api/store/hf/banners/v4",
        CLAIM_COUPON: "/api/store/cs/promo/acqn/{couponId}",
        FEEDBACK: "/api/v2/feedback/send",
        CI_TOKEN: "/api/cs/v2/images/tokens",
        PRIVACY_POLICY: "https://pages.xiaohongshu.com/data/sns/wx_mp_privacy_policy",
        GOODS_DETAIL_RELATED_NOTES: "/api/store/hf/items/{id}/notes",
        PAY: "/api/1/order/pay",
        PAY_CHECKOUT: "/api/store/oc/checkout",
        ORDER_DOWN: "/api/group_order",
        ORDER_ADDRESS: "/api/store/mc/addresses/v1",
        ORDER_INFO: "/api/order/detail_package/{id}",
        ORDER_LOGISTICS: "/api/store/logistics/tracking_records/{packageId}",
        ZONE_LEVEL: "/api/zone",
        ADDRESS: "/api/store/mc/addresses/v1",
        SAVE_ADDRESS: "/api/store/mc/address/v1",
        EDIT_ADDRESS: "/api/store/mc/address/v1/{aid}",
        DEFAULT_ADDRESS: "/api/store/mc/address/default/v1/{id}",
        ID_CARD_VERIFY: "/api/id_number/verify",
        CHECKOUT: "/api/store/oc/checkout",
        CREATE_ORDER: "/api/group_order",
        ORDER_LIST: "/api/store/oc/orders/v1",
        CREATE_ORDER_FROM_ITEM: "/group_order/instant_buy",
        PAYMENT: "/api/1/order/pay",
        PAYMENT_STATUS: "/api/1/order/infopay",
        MSG_SEND: "/api/sns/v1/wx_mp/template/send",
        TRACKING: "https://t.xiaohongshu.com/api/collect",
        TRACKING_TEST: "https://spltest.xiaohongshu.com/api/collect",
        INTEREST_TAGS: "/api/sns/v1/wx_mp/user/tag_recommend",
        QR_LINK: "/wx_mp_api/sns/v1/qrcode_route_url",
        ADS_QR_LINK: "https://pages.xiaohongshu.com/data/sns/mp_ads_qr_code_link",
        AB_TEST: "/fe_api/burdock/v2/experiment/mp/flag",
        COLLECT_FORM_ID: "/wx_mp_api/sns/v1/user/record_form",
        ACTIVITY_PINCH_GET_LAST_ITEM: "/api/sns/v1/wx_mp/pinch_face/latest",
        ACTIVITY_PINCH_ITEM_INFO: "/api/sns/v1/wx_mp/pinch_face/item/{itemId}",
        ACTIVITY_PINCH_UPDATE_ITEM: "/api/sns/v1/wx_mp/pinch_face/pinch_item/{itemId}",
        ACTIVITY_PINCH_CREATE_ITEM: "/api/sns/v1/wx_mp/pinch_face/item",
        ACTIVITY_PINCH_ACQUIRE_ITEM: "/api/sns/v1/wx_mp/pinch_face/acquire_pinch/{itemId}",
        ACTIVITY_PINCH_PART_LIST: "/api/sns/v1/wx_mp/pinch_face/part_list",
        ACTIVITY_PINCH_UPDATE_WEIXIN_INFO: "/api/sns/v1/wx_mp/pinch_face/update_user_info",
        ACTIVITY_PINCH_QR_CODE: "/api/sns/v1/wx_mp/pinch_face/gen_qrcode_url",
        ACTIVITY_PINCH_DEFAULT_INFO: "/api/sns/v1/wx_mp/pinch_face/get_default_face",
        ACTIVITY_BANNER_INFO: "https://pages.xiaohongshu.com/data/sns/mp_activity_banner",
        ACTIVITY_QR_CODE: "/api/sns/v1/wx_mp/activity/gen_qrcode_url",
        ACTIVITY_UPDATE_SESSION_KEY: "/api/sns/v1/wx_mp/activity/update_session_key",
        ACTIVITY_UPDATE_WEIXIN_INFO: "/api/sns/v1/wx_mp/activity/update_user_info",
        VIDEO_PACKET_OPEN: "/wx_mp_api/sns/v1/cny2019/video_packet",
        VIDEO_PACKET_CHECK_RED_PACKET: "/wx_mp_api/sns/v1/cny2019/{noteId}/check_red_packet",
        ACTIVITY_HEY: "/fe_api/burdock/v1/hey/{id}",
        ACTIVITY_HEY_INVITE_VIEWER: "/fe_api/burdock/v1/hey/invite",
        BRAND_PACKET_OPEN: "https://www.xiaohongshu.com/wx_mp_api/sns/v1/cny2019/brand_packet",
        BRAND_PACKET_PREPARE: "https://www.xiaohongshu.com/wx_mp_api/sns/v1/cny2019/brand_packet/prepare",
        BRAND_PACKET_FOLLOW: "https://www.xiaohongshu.com/wx_mp_api/sns/v1/cny2019/brand_packet/follow",
        INDEX_ACTIVITY_SWITCH: "https://pages.xiaohongshu.com/data/sns/mp_activity_switch",
        NOTE_DETAIL_ACTIVITY_SWITCH: "https://pages.xiaohongshu.com/data/sns/mp_note_detail_switch",
        REVIEW_MEMBER_INVITATION: "/api/store/mc/invitation/{invitationId}",
        JOIN_MEMBER_INVITATION: "/api/store/mc/join_invitation/{invitationId}",
        MEMBER_GOODS_IDS: "https://pages.xiaohongshu.com/data/fantasy/member_treasure_share/items",
        MEMBER_ORDER_CHECKOUT: "/api/store/mc/checkout",
        MEMBER_ORDER_CREATE: "/api/store/mc/orders",
        MEMBER_INFO: "/api/store/mc/landing",
        MEMBER_EVENT_POPUPS: "/api/store/mc/bullets",
        GOODS_SHARE: "/fe_api/sns/v1/wx_store/goods_share_info",
        VERTIFICATION_CODE: "/fe_api/burdock/weixin/v2/shield/captchaV2",
        LIVE: "/fe_api/burdock/v2/activity/live/{roomId}/info",
        PRODUCT_APPLY: "/api/store/experience_center/product/{productId}/user",
        PRODUCT_APPLICANTS: "/api/store/experience_center/product/{productId}/applicants",
        PRODUCT_NOTES: "/api/store/experience_center/product/{productId}/notes",
        SINGER_INFO: "https://pages.xiaohongshu.com/data/sns/mp_singer_albums_v2",
        SONGS_INFO: "https://pages.xiaohongshu.com/data/sns/mp_singer_songs",
        SONGS_RECOMMEND: "https://pages.xiaohongshu.com/data/sns/mp_singer_songs",
        GER_MP_QRCODE_URL: "/wx_mp_api/sns/v1/qrcode_image_url",
        GET_BRAND_LOTTERY_INFO: "/api/store/nb/lottery/info",
        GET_ACTIVITY_BANNER: "/fe_api/burdock/weixin/v2/banner",
        RECORD_PLATFORM_SOURCE: "/fe_api/burdock/weixin/v2/device/record",
        INIT_GEETEST: "/fe_api/burdock/weixin/v2/shield/registerGee",
        GET_SHARE_CODE: "/fe_api/burdock/weixin/v2/share/code"
    }
};

exports.config = e;

var _ = [ e.API_LIST.LOGIN, e.API_LIST.LOGOUT, e.API_LIST.MLOGIN, e.API_LIST.MOBILE_LOGIN, e.API_LIST.WX_MOBILE_LOGIN, e.API_LIST.TRACKING, e.API_LIST.TRACKING_TEST ];

exports.NO_SID_API_LIST = _;